version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.9

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run: ./mvnw -ntp clean install -Pci -Dlicense.skip=true

jobs:
  jdk21:
    docker:
      - image: cimg/openjdk:21.0.0
    environment:
      JVM_OPTS: -Xmx3200m
    steps: *build_steps

  snyk-scan:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run: ./mvnw -ntp clean install -Pci -Dlicense.skip=true -Dmaven.test.skip.exec=true
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: false
          skip-unresolved: false
          run-on-non-main: true
          additional-arguments: "--maven-aggregate-project"

workflows:
  build_and_test:
    jobs:
      - jdk21
      - general-platform-helpers/job-semgrep-scan:
           name: "Scan with Semgrep"
          context:
            - static-analysis
      - snyk-scan:
           name: execute-snyk
          context:
            - static-analysis
           requires:
             - prepare-snyk
